# Movie Recommender - Popularity based

In [6]:
import pandas as pd
import seaborn as sns

In [2]:
path = "../ml-latest-small/"
movies = pd.read_csv(f"{path}movies.csv")
links = pd.read_csv(f"{path}links.csv")
ratings = pd.read_csv(f"{path}ratings.csv")

In [55]:
ratings_dense_matrix = (
    ratings
        .drop(columns="timestamp")
        .groupby("movieId")
        .agg(mean_rating= ("rating", "mean"), count_rating= ("rating","count"))
        .assign(ratingtest = lambda x: x["mean_rating"] * (x["count_rating"] / 300))
        .round(1)
        
)
ratings_dense_matrix

         mean_rating  count_rating  ratingtest
movieId
1                3.9           215         2.8
2                3.4           110         1.3
3                3.3            52         0.6
4                2.4             7         0.1
5                3.1            49         0.5
...              ...           ...         ...
193581           4.0             1         0.0
193583           3.5             1         0.0
193585           3.5             1         0.0
193587           3.5             1         0.0
193609           4.0             1         0.0

[9724 rows x 3 columns]

## Recommender Function
**Input:** 
- ‘n’ (n is an integer, how many movies we wish to display)

**Output:** 
-  top n movies, so that you can populate the first row of WBSFLIX. Be careful not to recommend
any 5 star movies with only one rating.

In [58]:
def top_n_movies_chat_bot_popularity_based():
    n_movies= int(input("Hey I am a basic Movie recommender Bot. I can show you a list of the most popular Movies. \n How many movies should I show you?"))
    print(f"This are the top {n_movies} Movies:")
    return  (
        ratings_dense_matrix
            .sort_values("ratingtest", ascending=False)
            .query("count_rating > 1")
            .head(n_movies)
            .reset_index()
            .merge(movies)
            .filter(["title", "mean_rating","count_rating", "ratingtest"])
    )

top_n_movies_chat_bot_popularity_based()

This are the top 10 Movies:

,title,mean_rating,count_rating,ratingtest
0,"Shawshank Redemption, The (1994)",4.4,317,4.7
1,Forrest Gump (1994),4.2,329,4.6
2,Pulp Fiction (1994),4.2,307,4.3
3,"Silence of the Lambs, The (1991)",4.2,279,3.9
4,"Matrix, The (1999)",4.2,278,3.9
5,Star Wars: Episode IV - A New Hope (1977),4.2,251,3.5
6,Braveheart (1995),4.0,237,3.2
7,Schindler's List (1993),4.2,220,3.1
8,Fight Club (1999),4.3,218,3.1
9,Jurassic Park (1993),3.8,238,3.0